package twitter.modelo;
// Generated 28-may-2012 18:28:12 by Hibernate Tools 3.4.0.CR1



/**
 * Follows generated by hbm2java
 */
public class Follows  implements java.io.Serializable {

	private static final long serialVersionUID = -423047633146803710L;
	private Long id;
     private Usuarios usuariosBySeguidos;
     private Usuarios usuariosBySigo;

    public Follows() {
    }

    public Follows(Usuarios usuariosBySeguidos, Usuarios usuariosBySigo) {
       this.usuariosBySeguidos = usuariosBySeguidos;
       this.usuariosBySigo = usuariosBySigo;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Usuarios getUsuariosBySeguidos() {
        return this.usuariosBySeguidos;
    }
    
    public void setUsuariosBySeguidos(Usuarios usuariosBySeguidos) {
        this.usuariosBySeguidos = usuariosBySeguidos;
    }
    public Usuarios getUsuariosBySigo() {
        return this.usuariosBySigo;
    }
    
    public void setUsuariosBySigo(Usuarios usuariosBySigo) {
        this.usuariosBySigo = usuariosBySigo;
    }




}


