package twitter.modelo;

// Generated 28-may-2012 18:28:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Mensajes generated by hbm2java
 */
/**
 * @author Rafael de los Santos Guirado
 *
 */
public class Mensajes implements java.io.Serializable, Comparable<Mensajes> {

	private static final long serialVersionUID = 7549625905969959723L;
	private Integer id;
	private Usuarios usuarios;
	private String mensaje;
	private Date fecha;

	public Mensajes() {
	}

	public Mensajes(String mensaje, Date fecha) {
		this.mensaje = mensaje;
		this.fecha = fecha;
	}

	public Mensajes(Usuarios usuarios, String mensaje, Date fecha) {
		this.usuarios = usuarios;
		this.mensaje = mensaje;
		this.fecha = fecha;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Override
	public int compareTo(Mensajes o) {
		if (this.fecha.before(o.getFecha()))
			return 1;
		else if (this.fecha.after(o.getFecha()))
			return -1;
		else
			return 0;
	}

}
